# MySQL Configuration Profile
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/doctor_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Siva143sk}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=DoctorAppointmentSystemSecretKey2026ExpoSuperSecure256BitKeyMinimumSizeRequiredForHmacSha256!
app.jwt.expiration-ms=86400000
